CREATE TABLE `transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `reference` VARCHAR(100) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `fees` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `paid_at` DATETIME DEFAULT NULL,
  `channel` VARCHAR(50) NOT NULL,
  `currency` VARCHAR(10) NOT NULL,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `service` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

COMMIT;
